language: cpp

os:
  - linux
  - osx

compiler:
    - gcc
    - clang

addons:
  apt:
    packages:
    - libboost-all-dev
    - libfltk1.3-dev
    - freeglut3-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libxinerama-dev
    - libjpeg-dev
    - libxi-dev
    - libxmu-dev
    - fluid

matrix:
    exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

before_install:
  # OSX Setup
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update                                                                               ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install fltk freeglut                                                                ;fi

install:
  - git clone https://github.com/physycom/sysconfig.git
  - export WORKSPACE=$(pwd)
  - mkdir build && cd build

script:
  - cmake ..
  - cmake --build .
