
include(FindPackageHandleStandardArgs)


# Look for the header file.
FIND_PATH(NR3_INCLUDE_DIR NAMES nr3.h)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(NR3 DEFAULT_MSG NR3_INCLUDE_DIR)

# Copy the results to the output variables.
IF(NR3_FOUND)
	SET(NR3_INCLUDE_DIRS ${SQLITE3_INCLUDE_DIR})
ELSE(NR3_FOUND)
	SET(NR3_INCLUDE_DIRS)
ENDIF(NR3_FOUND)

MARK_AS_ADVANCED(NR3_INCLUDE_DIRS)

